- name: Install packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - libsane-dev
      - libjpeg-dev
      - libpng-dev
      - libavahi-client-dev
      - libusb-1.*-dev
      - git
      - cmake
      - g++
      - sane-airscan
      - sane-utils
      - avahi-daemon
  tags:
    - airsane

- name: Comment out "escl" in dll.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sane.d/dll.conf
    regexp: "^escl"
    line: "#escl"
  tags:
    - airsane

- name: Add "airsane" in dll.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sane.d/dll.conf
    insertbefore: apple
    line: airsane
  tags:
    - airsane

- name: Clone AirSane repository
  ansible.builtin.git: # noqa: latest[git]
    repo: 'https://github.com/SimulPiscator/AirSane.git'
    dest: "{{ ansible_env.HOME }}/Projects/AirSane"
  tags:
    - airsane

- name: Create a build directory if it does not exist
  ansible.builtin.file:
    path: "{{ airsane_build_dir }}"
    state: directory
    owner: pi
    group: pi
    mode: '0755'
  tags:
    - airsane

- name: Cmake AirSane
  ansible.builtin.command: cmake ../AirSane
  args:
    chdir: "{{ airsane_build_dir }}"
  register: cmake_airsane_output
  changed_when: cmake_airsane_output.rc != 0
  tags:
    - airsane

- name: Build AirSane
  ansible.builtin.make:
    chdir: "{{ airsane_build_dir }}"
  tags:
    - airsane

- name: Install AirSane
  become: true
  ansible.builtin.make:
    chdir: "{{ airsane_build_dir }}"
    target: install

- name: Enable airsane.service
  become: true
  ansible.builtin.service:
    name: airsaned
    state: restarted
    enabled: true
