- name: Install cups packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - cups
      - printer-driver-escpr
    state: latest

- name: Add user to lpadmin group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: lpadmin
    append: yes

- name: Setup cups
  become: true
  ansible.builtin.shell: cupsctl --remote-admin --remote-any --share-printers

- name: Restart cups service
  become: true
  ansible.builtin.service:
    name: cups
    state: restarted
