
- name: Create notebook directory
  ansible.builtin.file:
    path: /home/pi/notebooks
    state: directory
    mode: '0755'
  tags: jupyter

- name: Create repos directory
  ansible.builtin.file:
    path: /home/pi/repos
    state: directory
    mode: '0755'
  tags:
    - jupyter

- name: Install packages for jupyter
  become: yes 
  ansible.builtin.package:
    name: 
      - redis-server
      - libffi-dev
    state: latest
  tags:
    - jupyter
    - packages

- name: Install required python libraries for jupyter
  ansible.builtin.pip:
    name:
      - redis
      - setuptools
      - cffi
      - pygments
      - testresources
      - jupyterlab
      - matplotlib
      - ipympl
      - jupyter
  tags:
    - jupyter
    - python

- name: Git checkout of code 
  ansible.builtin.git:
    repo: "https://github.com/cvpeck/meas_rpi.git"
    dest: /home/pi/repos/meas_rpi
    version: cvp_devel
  tags:
    - jupyter
    - git

- name: Copy jupyter service file
  become: yes
  ansible.builtin.copy:
    src: /home/pi/repos/meas_rpi/jupyter/jupyter.service
    dest: /etc/systemd/system/
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  tags:
    - jupyter

- name: Enable jupyter service
  become: yes 
  ansible.builtin.service:
    name: jupyter
    enabled: yes
  tags:
    - jupyter

- name: Start service jupyter
  become: yes 
  ansible.builtin.service:
    name: jupyter
    state: started
  tags: jupyter

- name: Check if jupyter config already exists
  stat:
    path: "/home/pi/.jupyter/jupyter_notebook_config.py"
  register: jupyterconf_stat
  tags:
    - jupyter

- name: Generate jupyter notebook config
  ansible.builtin.shell: "/home/pi/.local/bin/jupyter notebook --generate-config"
  when: not jupyterconf_stat.stat.exists
  tags:
    - jupyter

- name: Link in jupyter examples
  ansible.builtin.copy:
    src: /home/pi/repos/meas_rpi/jupyter/examples
    dest: /home/pi/notebooks/examples
    follow: yes
    remote_src: yes
  tags:
    - jupyter

- name: Link in jupyter maintenance
  ansible.builtin.copy:
    src: /home/pi/repos/meas_rpi/jupyter/maintenance
    dest: /home/pi/notebooks/maintenance
    follow: yes
    remote_src: yes
  tags:
    - jupyter

- name: Create jupyter backups folder
  ansible.builtin.file:
    path: /home/pi/repos/meas_rpi/jupyter/maintenance/backups
    state: directory
    mode: '0755'
  tags:
    - jupyter

# ## set password later with: jupyter notebook password

- name: Create jupyter cron
  ansible.builtin.file:
    path: /home/pi/notebooks/cron
    state: directory
    mode: '0755'
  tags:
    - jupyter

- name: Create jupyter cron
  ansible.builtin.file:
    path: /home/pi/notebooks/cron
    state: directory
    mode: '0755'
  tags:
    - jupyter

- name: Create jupyter cron
  ansible.builtin.file:
    path: /home/pi/notebooks/cron/nightly
    state: directory
    mode: '0755'
  tags:
    - jupyter


- name: Create jupyter cron
  ansible.builtin.file:
    path: /home/pi/notebooks/cron/hourly
    state: directory
    mode: '0755'
  tags:
    - jupyter


- name: Add nightly backup script to sbin
  become: yes
  ansible.builtin.copy:
    src: /home/pi/repos/meas_rpi/scripts/cron_nightly.sh
    dest: /usr/sbin/
    follow: yes
    remote_src: yes
  tags:
    - jupyter

- name: Tighten up permissions on nightly scrpt
  ansible.builtin.file:
    path: /usr/sbin/cron_nightly.sh
    owner: root
    group: root
    mode: '0755'
  tags:
    - jupypter

- name: Nightly backup
  ansible.builtin.cron:
    name: "Nighly backup"
    minute: "30"
    hour: "2"
    job: "/usr/sbin/cron_nightly.sh"

- name: Add hourly backup script to sbin
  become: yes
  ansible.builtin.copy:
    src: /usr/sbin/cron_hourly.sh
    dest: /usr/sbin/
    follow: yes
    remote_src: yes
  tags:
    - jupyter

- name: Tighten up permissions on hourly scrpt
  ansible.builtin.file:
    path: /usr/sbin/cron_hourly.sh
    owner: root
    group: root
    mode: '0755'
  tags:
    - jupypter

- name: Hourly backup
  ansible.builtin.cron:
    name: "Hourly backup"
    minute: "0"
    job: "/usr/sbin/cron_hourly.sh"


