- name: Disable swap
  ansible.builtin.command: dphys-swapfile swapoff
  become: true
  tags:
    - swap

- name: Edit swap
  ansible.builtin.lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE'
    line: "CONF_SWAPSIZE={{ swap_size_mb }}"
  become: true
  tags:
    - swap

- name: Setup swap
  ansible.builtin.command: dphys-swapfile setup
  become: true
  tags:
    - swap

- name: Enable swap
  ansible.builtin.command: dphys-swapfile swapon
  become: true
  tags:
    - swap
