- name: Install vscode prerequisite packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - wget
      - gpg
      - apt-transport-https
  tags:
    - vscode

- name: Download key for vscode repoL
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: 0600
  tags:
    - vscode

- name: Delete existing key
  file:
    path: /tmp/microsoft.asc.gpg
    state: absent
  tags:
    - vscode

- name: Convert vscode key
  ansible.builtin.command:
    cmd: gpg --dearmor /tmp/microsoft.asc
  tags:
    - vscode

- name: Install vscode key
  become: yes
  ansible.builtin.command:
    cmd: install -D -o root -g root -m 644 /tmp/microsoft.asc.gpg /etc/apt/keyrings/packages.microsoft.gpg
  tags:
    - vscode    

- name: key to repo
  become: yes
  ansible.builtin.command:
    cmd: 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
  tags:
    - vscode

- name: Install vscode from deb package
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg: code
  tags:
    - vscode
