- name: Install vscode prerequisite packages
  become: true
  ansible.builtin.package:
    update_cache: true
    cache_valid_time: 3600
    name:
      - wget
      - gpg
      - apt-transport-https
      - libboost-all-dev
  tags:
    - vscode

- name: Download key for vscode repoL
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: '0600'
  tags:
    - vscode

- name: Delete existing key
  ansible.builtin.file:
    path: /tmp/microsoft.asc.gpg
    state: absent
  tags:
    - vscode

- name: Convert vscode key
  ansible.builtin.command:
    cmd: gpg --dearmor /tmp/microsoft.asc
  register: vscode_key_output
  changed_when: vscode_key_output.rc != 0
  tags:
    - vscode

- name: Install vscode key
  become: true
  ansible.builtin.command:
    cmd: install -D -o root -g root -m 644 /tmp/microsoft.asc.gpg /etc/apt/keyrings/packages.microsoft.gpg
  register: vscode_key_install
  changed_when: vscode_key_install.rc != 0
  tags:
    - vscode

- name: Key to repo
  become: true
  ansible.builtin.command:
    cmd: 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
  register: vscode_repo_output
  changed_when: vscode_repo_output.rc != 0
  tags:
    - vscode

- name: Install vscode from deb package
  become: true
  ansible.builtin.package:
    update_cache: true
    name: code
  tags:
    - vscode
